# Data Pre-Processing

## Import libraries

In [2]:
import numpy as np
import pandas as pd

In [ ]:
dataset = pd.read_csv('/home/jinx/Belajar/Learn to create Machine Learning Algorithms in Python and R from two Data Science experts Code templates included/Preprocessing data/exercise_4.csv')

# mengambil semua nilai baris kecuali kolom terakhir (:-1)
# iloc mengambil data beradasarkan kolom dengan indeks sbg numerik/angka dan bentuk data nya menjadi array
# x = dataset.iloc[:, :-1].values
# .drop menghapus kolom tertentu tanpa mengubah bentuk data nta
x = dataset.drop('target', axis=1)
# y mengambil data pada kolom terakhir
# y = dataset.iloc[:, -1].values
y = dataset['target']

In [35]:
print(x)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]


In [36]:
print(y)

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int64


## Identify if dataset is have null value

In [37]:
missing_data = dataset.isnull().sum().sum() # jika nilai nya NaN
# missing_data = (dataset == 0).sum().sum() # jika ada nilai 0

print(missing_data)

0


## Taking care of Missing Data

In [38]:
# library untuk mengisi nilai yg missing value/ cell yg nilai nya kosong
# from sklearn.impute import SimpleImputer
# imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# imputer.fit(x[:, 1:3]) # artinya kolom yg di pilih 1 hingga 3 (tapi bukan indeks 3, tapi 3 -1 = 2). krna indeks dari 0
# x[:, 1:3] = imputer.transform(x[:, 1:3])
# imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# imputer.fit(dataset)
# x = imputer.transform(dataset)

In [39]:
# print(x)

## Encoding categorical data
mengubah nilai categorical / string menjadi sebuah nilai numerik

### Encoding independent variables

In [40]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder

# colTrans = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# x = colTrans.fit_transform(x)
# x = np.array(x)

In [41]:
# print(x)

### Encoding dependent variables

In [42]:
# from sklearn.preprocessing import LabelEncoder
# labEnc = LabelEncoder()
# y = labEnc.fit_transform(y)

In [43]:
# print(y)

## Splitting dataset to training and testing 

In [44]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 42)

In [45]:
print(x_train)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                 4.6               3.6                1.0               0.2
15                 5.7               4.4                1.5               0.4
65                 6.7               3.1                4.4               1.4
11                 4.8               3.4                1.6               0.2
42                 4.4               3.2                1.3               0.2
..                 ...               ...                ...               ...
71                 6.1               2.8                4.0               1.3
106                4.9               2.5                4.5               1.7
14                 5.8               4.0                1.2               0.2
92                 5.8               2.6                4.0               1.2
102                7.1               3.0                5.9               2.1

[120 rows x 4 columns]


In [46]:
print(x_test)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
73                 6.1               2.8                4.7               1.2
18                 5.7               3.8                1.7               0.3
118                7.7               2.6                6.9               2.3
78                 6.0               2.9                4.5               1.5
76                 6.8               2.8                4.8               1.4
31                 5.4               3.4                1.5               0.4
64                 5.6               2.9                3.6               1.3
141                6.9               3.1                5.1               2.3
68                 6.2               2.2                4.5               1.5
82                 5.8               2.7                3.9               1.2
110                6.5               3.2                5.1               2.0
12                 4.8               3.0                1.4     

In [47]:
print(y_train)

22     0
15     0
65     1
11     0
42     0
      ..
71     1
106    2
14     0
92     1
102    2
Name: target, Length: 120, dtype: int64


In [48]:
print(y_test)

73     1
18     0
118    2
78     1
76     1
31     0
64     1
141    2
68     1
82     1
110    2
12     0
36     0
9      0
19     0
56     1
104    2
69     1
55     1
132    2
29     0
127    2
26     0
128    2
131    2
145    2
108    2
143    2
45     0
30     0
Name: target, dtype: int64


## Feature Scalling

### untuk menyelaraskan nilai numerik agar rentan nilai nya tidak terlalu jauh (lebih konsisten)

In [56]:
from sklearn.preprocessing import StandardScaler
StandScaler = StandardScaler()
x_train = StandScaler.fit_transform(x_train)
x_test = StandScaler.transform(x_test) 
# y_train = StandScaler.fit_transform(y_train)
# y_test = StandScaler.fit_transform(y_test)

In [57]:
print(x_train)

[[-1.47393679  1.20365799 -1.56253475 -1.31260282]
 [-0.13307079  2.99237573 -1.27600637 -1.04563275]
 [ 1.08589829  0.08570939  0.38585821  0.28921757]
 [-1.23014297  0.75647855 -1.2187007  -1.31260282]
 [-1.7177306   0.30929911 -1.39061772 -1.31260282]
 [ 0.59831066 -1.25582892  0.72969227  0.95664273]
 [ 0.72020757  0.30929911  0.44316389  0.4227026 ]
 [-0.74255534  0.98006827 -1.27600637 -1.31260282]
 [-0.98634915  1.20365799 -1.33331205 -1.31260282]
 [-0.74255534  2.32160658 -1.27600637 -1.44608785]
 [-0.01117388 -0.80864948  0.78699794  0.95664273]
 [ 0.23261993  0.75647855  0.44316389  0.55618763]
 [ 1.08589829  0.08570939  0.55777524  0.4227026 ]
 [-0.49876152  1.87442714 -1.39061772 -1.04563275]
 [-0.49876152  1.4272477  -1.27600637 -1.31260282]
 [-0.37686461 -1.47941864 -0.01528151 -0.24472256]
 [ 0.59831066 -0.58505976  0.78699794  0.4227026 ]
 [ 0.72020757  0.08570939  1.01622064  0.8231577 ]
 [ 0.96400139 -0.13788033  0.38585821  0.28921757]
 [ 1.69538284  1.20365799  1.36

In [58]:
print(x_test)

[[ 0.14443512 -0.63451517  0.45110832 -0.07943674]
 [-0.33701527  2.00929805 -1.2060243  -1.20827465]
 [ 2.07023667 -1.16327782  1.66633891  1.30025404]
 [ 0.02407252 -0.37013385  0.34063282  0.29684256]
 [ 0.98697329 -0.63451517  0.50634608  0.17141613]
 [-0.69810306  0.95177276 -1.3164998  -1.08284822]
 [-0.45737787 -0.37013385 -0.15650697  0.04598969]
 [ 1.10733589  0.15862879  0.67205934  1.30025404]
 [ 0.26479771 -2.22080311  0.34063282  0.29684256]
 [-0.21665267 -0.8988965   0.00920629 -0.07943674]
 [ 0.6258855   0.42301012  0.67205934  0.92397473]
 [-1.42027864 -0.10575253 -1.37173756 -1.45912752]
 [-0.57774046  1.21615408 -1.42697531 -1.33370109]
 [-1.29991605  0.15862879 -1.3164998  -1.45912752]
 [-1.05919085  2.00929805 -1.3164998  -1.20827465]
 [ 0.38516031  0.68739144  0.45110832  0.422269  ]
 [ 0.6258855  -0.10575253  1.05872362  1.1748276 ]
 [-0.45737787 -1.42765914  0.00920629 -0.20486318]
 [-0.33701527 -0.63451517  0.34063282  0.04598969]
 [ 0.50552291 -0.63451517  0.94

In [54]:
print(y_train)

22     0
15     0
65     1
11     0
42     0
      ..
71     1
106    2
14     0
92     1
102    2
Name: target, Length: 120, dtype: int64


In [55]:
print(y_test)

73     1
18     0
118    2
78     1
76     1
31     0
64     1
141    2
68     1
82     1
110    2
12     0
36     0
9      0
19     0
56     1
104    2
69     1
55     1
132    2
29     0
127    2
26     0
128    2
131    2
145    2
108    2
143    2
45     0
30     0
Name: target, dtype: int64
