# Data Pre-Processing

## Import libraries

In [101]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [102]:
dataset = pd.read_csv('/home/jinx/Belajar/Learn to create Machine Learning Algorithms in Python and R from two Data Science experts Code templates included/Preprocessing data/Data.csv')

# mengambil semua nilai baris kecuali kolom terakhir (:-1)
# iloc mengambil data beradasarkan kolom dengan indeks sbg numerik/angka
x = dataset.iloc[:, :-1].values

# y mengambil data pada kolom terakhir
y = dataset.iloc[:, -1].values

In [103]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [104]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Identify if dataset is have null value

In [105]:
missing_data = dataset.isnull().sum().sum() # jika nilai nya NaN
# missing_data = (dataset == 0).sum().sum() # jika ada nilai 0

print(missing_data)

2


## Taking care of Missing Data

In [106]:
# library untuk mengisi nilai yg missing value/ cell yg nilai nya kosong
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3]) # artinya kolom yg di pilih 1 hingga 3 (tapi bukan indeks 3, tapi 3 -1 = 2). krna indeks dari 0
x[:, 1:3] = imputer.transform(x[:, 1:3])
# imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
# imputer.fit(dataset)
# x = imputer.transform(dataset)

In [107]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data
mengubah nilai categorical / string menjadi sebuah nilai numerik

### Encoding independent variables

In [108]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

colTrans = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = colTrans.fit_transform(x)
x = np.array(x)

In [109]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding dependent variables

In [110]:
from sklearn.preprocessing import LabelEncoder
labEnc = LabelEncoder()
y = labEnc.fit_transform(y)

In [111]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting dataset to training and testing 

In [126]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [130]:
print(x_train[:, 3:])
print(x_train)

[[38.77777777777778 52000.0]
 [40.0 63777.77777777778]
 [44.0 72000.0]
 [38.0 61000.0]
 [27.0 48000.0]
 [48.0 79000.0]
 [50.0 83000.0]
 [35.0 58000.0]]
[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [129]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [131]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [132]:
print(y_test)

[0 1]


## Scalling feature


In [134]:
from sklearn.preprocessing import StandardScaler
StandScaler = StandardScaler()
x_train[:, 3:] = StandScaler.fit_transform(x_train[:, 3:])
x_test[:, 3:] = StandScaler.transform(x_test[:, 3:]) 

In [135]:
print(x_train)

[[0.0 0.0 1.0 -0.1915918438457856 -1.0781259408412427]
 [0.0 1.0 0.0 -0.014117293757057902 -0.07013167641635401]
 [1.0 0.0 0.0 0.5667085065333239 0.6335624327104546]
 [0.0 0.0 1.0 -0.3045301939022488 -0.30786617274297895]
 [0.0 0.0 1.0 -1.901801144700799 -1.4204636155515822]
 [1.0 0.0 0.0 1.1475343068237056 1.2326533634535488]
 [0.0 1.0 0.0 1.4379472069688966 1.5749910381638883]
 [1.0 0.0 0.0 -0.7401495441200352 -0.5646194287757336]]


In [136]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
